[project]
name = "app-blogs"
version = "2.0.0"
description = "Add Blogs to your web page"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bcrypt== 5.0.0",
    "cryptography==46.0.3",
    "fastapi==0.128.0",
    "pydantic[email]==2.12.5",
    "PyJWT==2.10.1",
    "python-dotenv==1.2.1",
    "sqlalchemy==2.0.45",
    "strawberry-graphql[fastapi]>=0.288.2",
    "uvicorn==0.40.0",
]


[project.scripts]
app = "src.app.main:app"

[dependency-groups]
dev = [
    "pytest>=9.0.2",
]
